spring:

  datasource:
    url: jdbc:mysql://localhost:3306/teaching_management?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

#logging:
#  level:
#    org:
#      springframework: DEBUG
#      hibernate: DEBUG